# Generated by Django 3.2.12 on 2022-05-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
